# Generated by Django 5.0 on 2024-01-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_subject_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
