# Generated by Django 5.0 on 2024-01-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='self_intro',
            field=models.TextField(default=''),
        ),
    ]
